export const SWAGGER_REFRESH_COOKIE_NAME_PLACEHOLDER =
  '__REFRESH_COOKIE_NAME__';

export const SWAGGER_CSRF_COOKIE_NAME_PLACEHOLDER = '__CSRF_COOKIE_NAME__';

export const SWAGGER_CSRF_HEADER_NAME_PLACEHOLDER = '__CSRF_HEADER_NAME__';
